# Generated by Django 2.2.2 on 2020-01-25 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyOption',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('active', models.IntegerField(default=1)),
                ('period', models.CharField(default='all', max_length=100)),
            ],
        ),
    ]
