# Generated by Django 2.2.2 on 2020-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersTZ',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
    ]
