# Generated by Django 2.2.2 on 2020-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_teacherstz'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstz',
            name='orderindex',
            field=models.IntegerField(default=0),
        ),
    ]
