# Generated by Django 2.2.2 on 2020-01-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0003_teacherstz_orderindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(default=1)),
                ('orderindex', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
    ]
