# Generated by Django 2.2.2 on 2020-01-28 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0004_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('from_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherstz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
