# Generated by Django 2.2.2 on 2020-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0006_auto_20200128_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstz',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
