# Generated by Django 2.2.2 on 2020-01-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0008_texttz'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstz',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
