# Generated by Django 2.2.2 on 2020-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0009_teacherstz_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
