# Generated by Django 2.2.14 on 2020-09-02 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0011_auto_20200514_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to='quiz')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('result', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.Quiz')),
            ],
        ),
    ]
